### ISSUE TITLE
app.css missing

### ISSUE THREAD

**Issue by rmrao12** [SMQuadri/Nike-Shoes-ECommerce-Site#1]
app.css file is missing and how to run this specific project there are no clear instructions kindly tell me cz i am not abe to run this

**Comment by SMQuadri** [comment]
I don't have an app.css file for this project. All the styles of various components resides in their separate CSS stylesheets. Whereas the global styles have been declared in index.css file. Just delete the app.css file from your project's folder structure and remove its import statement in app.js file.
There are no complicated instructions to run this project and is easy. The only things you need to do are;
1) Setup project in Firebase.
2) Enable its hosting option to later make your project live on the internet.
3) Also, what you need to do is, in your project's firebase console go to;
settings > project settings > Your apps > SDK setup and configuration > Config.  Then copy the code snippet and paste it inside your working react folder structure in;  src > firebase.js
4) In my project, I have setup the user's authentication and tracking only through email and password. This can be done in your Firebase's project console > Authentication > Sign in method > Email/Password (Enable it).
5) Also, I have integrated Stripe API to process dummy payment transactions through card. What you need to do is just go to the Stripe API and follow the basic payment setup. After this, you will get the corresponding Stripe API key. Copy it and paste it in;
src > components > Checkout > TotalPrice > TotalPrice.js (line 39).

**Comment by rmrao12** [comment]
i deleted the app.css error but now when i run it npm start it runs but a blank page is displaying

**Comment by SMQuadri** [comment]
You might be getting errors i think !!
It is because the project contains various Firebase functions which will run only when you create your project in Firebase and paste the config file in firebase.js file.

**Comment by rmrao12** [comment]
i paste it in the config file still nothing did everything u said. please solve this i need your project for testing purpose

**Comment by SMQuadri** [comment]
Bro, it would be better if we connect on whatsapp and talk about it there. Iam unable to recognize the fault in your project from the statements you are giving.
+91 9121980842

**Comment by rmrao12** [comment]
okay bro
